### PR TITLE
Feature to exercise #877

### PR DESCRIPTION
**Pull request by tiennou**
This is a simplification of my failing #877 workflow, so at least I can be sure that it's not some unrelated, local-only occurrence.

### CODE REVIEW

**Comment by tiennou** [comment]
At least here it seems to fail with what I'm seeing when I'm "workflowing", eg the automatic remote selection gets confused and uses whatever remote is the first one.

**Comment by mislav** [comment]
Thanks for the failing test! The head/base resolution for PR is broken is all sorts of ways right now and is high on my list to fix next. There are so many edge-case problems with it, that I'll probably end up rewriting the whole head/base resolution logic instead of tweaking existing code. However,  I won't be able to get to this before 2 weeks form now, because I'm offline on vacation.

Until then, whenever you have a problem, simply specify head (and/or base) explicitly.

**Comment by tiennou** [comment]
No problem, it can wait. I may try to take a look, but I'm not a Go-er, so that might be out of my reach, we'll see. Have a nice vacation, sir !

**Comment by mislav** [comment]
I was not a Go-er until somone entirely rewrote hub from Ruby into Go and it was faster ;)

**Pull request closed without merging**
